name    'jhoblitt-tzdata'
version '1.0.1'

author 'Joshua Hoblitt <jhoblitt@cpan.org>'
license 'Apache'
project_page 'https://github.com/jhoblitt/puppet-tzdata'
source 'https://github.com/jhoblitt/puppet-tzdata.git'
summary 'Install/update the Olson timezone database'
description 'Install/update the Olson timezone database'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
